### ISSUE TITLE
Cookieless Auth

### ISSUE THREAD

**Issue by christianpappenberger** [simonhaenisch/koa-shopify-auth#1]
Hi Simon,

thanks for creating this repo with all the improvements!

As you probably know koa-auth is currently struggling with aligning to the new Safari policy where all 3rd party cookies are blocked. Do you have an idea how to fix it?

Thanks
Chris

**Comment by simonhaenisch** [comment]
Hi, no sorry I haven't dealt with that yet. Do you have any more info about what exactly isn't working? There's the ITP helper code in this repository which I didn't write, that's supposed to make this work in Safari. Just to be sure, by new Safari you mean Safari 14? I did test it with the previous Safari and it was working. I'll probably be able to look into this at some point but can't really give you a timeline at the moment. Might take a few months.

**Comment by chris8447** [comment]
Hi Simon,
Well I am currently experiencing a redirect loop. The current koa-auth package from Shopify tries to get the user agreement to access the cookies. From the Shopify forums people say that this solution worked for some time as you also said. However, with the current release of Safari 14 it is not working anymore.
